all:
	g++ buscar_valor_memoria.cpp -o ./out/buscar_memoria
	g++ buscar_valor_archivo.cpp -o ./out/buscar_archivo
	g++ pre_orden_memoria.cpp -o ./out/pre_orden_memoria
	g++ pre_orden_archivo.cpp -o ./out/pre_orden_archivo
	g++ niveles_archivo.cpp -o ./out/niveles_archivo
	g++ niveles_memoria.cpp -o ./out/niveles_memoria
	g++ crear_arbol_lleno.cpp -o ./out/crear_arbol
	g++ crear_arbol_ordenado.cpp -o ./out/crear_arbol_ordenado
