all:
	/usr/bin/g++ buscar_valor_memoria.cpp -o ./out/buscar_memoria
	/usr/bin/g++ buscar_valor_archivo.cpp -o ./out/buscar_archivo

	/usr/bin/g++ pre_orden_memoria.cpp -o ./out/pre_orden_memoria
	/usr/bin/g++ pre_orden_archivo.cpp -o ./out/pre_orden_archivo

	/usr/bin/g++ niveles_archivo.cpp -o ./out/niveles_archivo
	/usr/bin/g++ niveles_memoria.cpp -o ./out/niveles_memoria

	/usr/bin/g++ crear_arbol_lleno.cpp -o ./out/crear_arbol
	/usr/bin/g++ crear_arbol_ordenado.cpp -o ./out/crear_arbol_ordenado