all:
	/usr/bin/g++ buscar_valor_memoria.cpp -o buscar_memoria
	/usr/bin/g++ buscar_valor_archivo.cpp -o buscar_archivo

	/usr/bin/g++ pre_orden_memoria.cpp -o pre_orden_memoria
	/usr/bin/g++ pre_orden_archivo.cpp -o pre_orden_archivo

	/usr/bin/g++ niveles_archivo.cpp -o niveles_archivo
	/usr/bin/g++ niveles_memoria.cpp -o niveles_memoria

	/usr/bin/g++ crear_arbol_lleno.cpp -o crear_arbol
	/usr/bin/g++ crear_arbol_ordenado.cpp -o crear_arbol_ordenado